routes/web.php
<?php

use Illuminate\Support\Facades\Route;
Route::get('/', function () {
    return view('welcome');
});
Route::prefix('tracks')->as('tracks.')->namespace('App\Http\Controllers\Tracks')->group(function() {
    Route::prefix('track-1')->namespace('Track1')->as('track1.')->group(function() {
        Route::prefix('review')->controller('ReviewController')->as('review.')->group(function() {
            Route::get('/','index')->name('index');
            Route::get('/overview','overview')->name('overview');
            Route::prefix('ke-hoach')->group(function() {
                Route::get('/','kehoach')->name('kehoach');
                Route::get('/{id}','kehoachdetail')->name('kehoachdetail');
            });
            Route::prefix('san-xuat')->group(function() {
                Route::get('/','sanxuat')->name('sanxuat');
                Route::get('/{id}','sanxuatdetail')->name('sanxuatdetail');
            });
          
         
        });
    });
    Route::prefix('track-2')->namespace('Track2')->as('track2.')->group(function() {
        Route::prefix('review')->controller('ReviewController')->as('review.')->group(function() {
            Route::get('/','index')->name('index');
            Route::get('/overview','overview')->name('overview');
            Route::prefix('phan-phoi')->group(function() {
                Route::get('/','phanphoi')->name('phanphoi');
                Route::get('/{id}','phanphoidetail')->name('phanphoidetail');
            });
            Route::prefix('phat-trien-thi-truong')->group(function() {
                Route::get('/','phattrienthitruong')->name('phattrienthitruong');
                Route::get('/{id}','phattrienthitruongdetail')->name('phattrienthitruongdetail');
            });
        });
    });
    Route::prefix('track-3')->namespace('Track3')->as('track3.')->group(function() {
        Route::prefix('review')->controller('ReviewController')->as('review.')->group(function() {
            Route::get('/','index')->name('index');
            Route::get('/overview','overview')->name('overview');
            Route::prefix('ho-tro')->group(function() {
                Route::get('/','hotro')->name('hotro');
                Route::get('/{id}','hotrodetail')->name('hotrodetail');
            });
        });
    });
  
});

app/Models/User.php
<?php

namespace App\Models;

// use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * Get the attributes that should be cast.
     *
     * @return array<string, string>
     */
    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
        ];
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

abstract class Controller
{
    //
}

app/Http/Controllers/Tracks/Track1/KeHoachController.php
<?php

namespace App\Http\Controllers\Tracks\Track1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class KeHoachController extends Controller
{
    protected $pathView = "tracks.track1.kehoach.";
    public function index(Request $request)
    {
        return view($this->pathView. 'index');
    }
}

app/Http/Controllers/Tracks/Track1/ReviewController.php
<?php

namespace App\Http\Controllers\Tracks\Track1;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    protected $pathView = "tracks.track1.reviews.";
    public function index(Request $request)
    {
        return view($this->pathView. 'index');
    }
    public function kehoach(Request $request)
    {
        return view($this->pathView. 'kehoach');
    }
    public function kehoachdetail(Request $request) {
        $id = $request->id;
        $nextId = $id +  1;
        $backId = $id > 1 ? $id - 1 : 1;
      
      
       
        return view($this->pathView. 'kehoach.detail-'.$id,compact('nextId','backId'));
    }
    public function sanxuat(Request $request)
    {
        return view($this->pathView. 'sanxuat');
    }
    public function sanxuatdetail(Request $request) {
        $id = $request->id;
        $nextId = $id +  1;
        $backId = $id > 1 ? $id - 1 : 1;
      
        return view($this->pathView. 'sanxuat.detail-'.$id,compact('nextId','backId'));
    }
}

app/Http/Controllers/Tracks/Track2/ReviewController.php
<?php

namespace App\Http\Controllers\Tracks\Track2;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    protected $pathView = "tracks.track2.reviews.";
    public function index(Request $request)
    {
        return view($this->pathView. 'index');
    }
    public function phanphoi(Request $request)
    {
        return view($this->pathView. 'phanphoi');
    }
    public function phanphoidetail(Request $request) {
        $id = $request->id;
        $nextId = $id +  1;
        $backId = $id > 1 ? $id - 1 : 1;
      
       
        return view($this->pathView. 'phanphoi.detail-'.$id,compact('nextId','backId'));
    }
    public function phattrienthitruong(Request $request)
    {
        return view($this->pathView. 'phattrienthitruong');
    }
    public function phattrienthitruongdetail(Request $request) {
        $id = $request->id;
        $nextId = $id +  1;
        $backId = $id > 1 ? $id - 1 : 1;
      
        return view($this->pathView. 'phattrienthitruong.detail-'.$id,compact('nextId','backId'));
    }
}

app/Http/Controllers/Tracks/Track3/ReviewController.php
<?php

namespace App\Http\Controllers\Tracks\Track3;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ReviewController extends Controller
{
    protected $pathView = "tracks.track3.reviews.";
    public function index(Request $request)
    {
        return view($this->pathView. 'index');
    }
    public function hotro(Request $request)
    {
        return view($this->pathView. 'hotro');
    }
    public function hotrodetail(Request $request) {
        $id = $request->id;
        $nextId = $id +  1;
        $backId = $id > 1 ? $id - 1 : 1;
      
       
        return view($this->pathView. 'hotro.detail-'.$id,compact('nextId','backId'));
    }
}

resources/views/tracks/track1/reviews/index.blade.php
@extends('layouts/review')
@section('track_number','track-2')
@section('content')
    <h2 class="review-title">
        ĐÂU LÀ CÁCH CÁC CƯ DÂN TẠI THÀNH PHỐ HẠNH PHÚC CÙNG NHAU KIẾN TẠO VÀ LAN TỎA ĐIỀU KỲ DIỆU ĐẾN CHO CỘNG ĐỒNG TẠI
        VƯƠNG QUỐC CỦA CHÚNG TA? 
    </h2>
    <div class="review-index">
       <a href="{{route('tracks.track1.review.kehoach')}}"> <img src="{{asset('img/review-overview.png')}}" alt=""></a>
    </div>
@endsection

resources/views/tracks/track1/reviews/kehoach.blade.php
@extends('layouts/review')
@section('track_number', 'track-2')
@section('content')
    <div class="box-title">
        <p> Để có thể chinh phục các thử thách tại Thị Trấn một cách xuất sắc nhất và trở thành những Người dẫn đầu Tương
            lai – Future Shapers, hãy cùng tìm hiểu về khâu đầu tiên cực kỳ quan trọng – Lập kế hoạch được diễn ra thế nào
            nhé:
        </p>
    </div>
    <div class="rows-3 row-cards">
        <div class="row-item">
            <a href="{{route('tracks.track1.review.kehoachdetail',['id' => 1])}}"> <img src="{{ asset('img/hologram-box-1.png') }}" alt=""></a>
        </div>
        <div class="row-item">
            <a href="{{route('tracks.track1.review.kehoachdetail',['id' => 2])}}"><img src="{{ asset('img/hologram-box-2.png') }}" alt=""></a>
        </div>
        <div class="row-item">
            <a href="{{route('tracks.track1.review.kehoachdetail',['id' => 3])}}"> <img src="{{ asset('img/hologram-box-3.png') }}" alt=""></a>
        </div>
    </div>
@endsection

resources/views/tracks/track1/reviews/kehoach/detail-1.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-vai-tro-y-nghia.png') }}" alt="">
    </div>
    <div class="review-detail-content kehoach-detail">
        <div class="review-flex-center">
            <div class="box-label">
             <p>   Đưa ra những dự báo chính xác về doanh số thông qua sự am hiểu sâu sắc về tình hình thị trường để  từ đó lên kế hoạch sản xuất chi tiết nhằm:</p>
            </div>
            <div class="box-label-desc-wrap">
                <div class="box-label-desc">
                    <ul>
                        <li>Tối ưu hóa các nguồn lực</li>
                        <li> Đáp ứng nhu cầu khách hàng, </li>
                        <li> Đạt được lợi nhuận cao
                        </li>
                        <li>Gia tăng năng suất.</li>
                    </ul>
                </div>
            </div>
        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track1.review.kehoach') }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track1.review.kehoachdetail', ['id' => $nextId]) }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track1/reviews/kehoach/detail-3.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-buc-tranh-thanh-cong.png') }}" alt="">
    </div>
    <div class="review-detail-content kehoach-detail detail-3 ">
        <div class="review-flex-center">
            <div class="rows-3">
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/carbon_forecast-hail.png') }}" alt="">
                    </div>
                    <p> Dự báo chính xác</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/icon-park-outline_optimize.png') }}" alt="">
                    </div>
                    <p> Tối ưu hóa nguồn lực</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/hugeicons_waste-restore.png') }}" alt="">
                    </div>
                    <p> Giảm lãng phí</p>
                </div>
            </div>


        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track1.review.kehoachdetail', ['id' => $backId]) }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track1.review.sanxuat') }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track1/reviews/sanxuat.blade.php
@extends('layouts/review')
@section('track_number', 'track-2')
@section('content')
    <div class="box-title">
        <p>Sau khâu Lập Kế Hoạch, hãy cùng theo dõi những nội dung dưới đây để tìm hiểu về khâu “Sản xuất” và chuẩn bị sẵn cho mình những bí kíp thật xịn để tham gia các thử thách tại Chặng 1 nhé:
        </p>
    </div>
    <div class="rows-3 row-cards">
        <div class="row-item">
            <a href="{{route('tracks.track1.review.sanxuatdetail',['id' => 1])}}"> <img src="{{ asset('img/hologram-box-1.png') }}" alt=""></a>
        </div>
        <div class="row-item">
            <a href="{{route('tracks.track1.review.sanxuatdetail',['id' => 2])}}"><img src="{{ asset('img/hologram-box-2.png') }}" alt=""></a>
        </div>
        <div class="row-item">
            <a href="{{route('tracks.track1.review.sanxuatdetail',['id' => 3])}}"> <img src="{{ asset('img/hologram-box-3.png') }}" alt=""></a>
        </div>
    </div>
@endsection

resources/views/tracks/track1/reviews/sanxuat/detail-1.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-vai-tro-y-nghia.png') }}" alt="">
    </div>
    <div class="review-detail-content">
        <div class="review-flex-center">
            <div class="box-label">
                <p>Kiểm soát và tối ưu hóa toàn bộ quy trình sản xuất từ chuyển hóa nguyên liệu thô thành thành phẩm, đảm bảo chất lượng sản phẩm và tối ưu chi phí sản xuất.</p>
            </div>
      
        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track1.review.sanxuat') }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track1.review.sanxuatdetail', ['id' => $nextId]) }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track1/reviews/sanxuat/detail-2.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-chuoi-gia-tri.png') }}" alt="">
    </div>
   
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track1.review.sanxuatdetail', ['id' => $backId]) }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track1.review.sanxuatdetail', ['id' => $nextId]) }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track1/reviews/sanxuat/detail-3.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-buc-tranh-thanh-cong.png') }}" alt="">
    </div>
    <div class="review-detail-content kehoach-detail detail-3 sanxuat-detail ">
        <div class="review-flex-center">
            <div class="rows-3">
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/fluent_autosum-16-filled.png') }}" alt="">
                    </div>
                    <p> Tổng năng suất chuỗi cung ứng</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/icon-park-outline_manual-gear.png') }}" alt="">
                    </div>
                    <p> Hiệu quả hoạt động dây chuyền</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/healthicons_chart-death-rate-increasing.png') }}" alt="">
                    </div>
                    <p> Tỉ lệ sử dụng nước & năng lượng</p>
                </div>
            </div>


        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track1.review.sanxuatdetail', ['id' => $backId]) }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track2.review.index') }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track2/reviews/index.blade.php
@extends('layouts/review')
@section('track_number','track-1')
@section('content')
    <h2 class="review-title">
        ĐÂU LÀ CÁCH CÁC CƯ DÂN TẠI THÀNH PHỐ HẠNH PHÚC CÙNG NHAU KIẾN TẠO VÀ LAN TỎA ĐIỀU KỲ DIỆU ĐẾN CHO CỘNG ĐỒNG TẠI
        VƯƠNG QUỐC CỦA CHÚNG TA?
    </h2>
    <div class="review-index">
       <a href="{{route('tracks.track2.review.phanphoi')}}"> <img src="{{asset('img/review-index-track-2.png')}}" alt=""></a>
    </div>
@endsection

resources/views/tracks/track2/reviews/phanphoi.blade.php
@extends('layouts/review')
@section('track_number', 'track-2')
@section('content')
    <div class="phanphoi-index">
        <div class="box-title">
            <p> Hãy cùng tìm hiểu những thông tin dưới đây trước khi chinh phục các thử thách tại khâu <br> Phân Phối tại
                Thị
                Trấn Hạnh Phúc nhé:
            </p>
        </div>
        <div class="box-label phanphoi-box-label">
            <p> Chuỗi phân phối có vai trò quản lý và điều phối toàn bộ quy trình lưu trữ và vận chuyển hàng hóa từ nhà
                máy/trung tâm phân phối đến các điểm bán hàng trên toàn quốc, trong đó gồm việc tối ưu hóa Phương thức lưu
                trữ,
                vận tải và mạng lưới phân phối nhằm đảm bảo hiệu quả, an toàn và dịch vụ khách hàng tốt nhất.</p>
        </div>
        <div class="rows-3">
            <div class="row-item phanphoi-label-item">
                <a href="{{ route('tracks.track2.review.phanphoidetail', ['id' => 1]) }}"><img
                        src="{{ asset('img/phanphoi-1.png') }}" alt=""></a>
            </div>
            <div class="row-item phanphoi-label-item">
                <a href="{{ route('tracks.track2.review.phanphoidetail', ['id' => 2]) }}"><img
                        src="{{ asset('img/phanphoi-2.png') }}" alt=""></a>
            </div>
            <div class="row-item phanphoi-label-item">
                <a href="{{ route('tracks.track2.review.phanphoidetail', ['id' => 3]) }}"><img
                        src="{{ asset('img/phanphoi-3.png') }}" alt=""></a>
            </div>
        </div>
        <div class="review-buttons">
            <div class="btn-back">
                <a href="{{ route('tracks.track2.review.index') }}">TRỞ LẠI</a>
            </div>
            <div class="btn-next">
                <a href="{{ route('tracks.track2.review.phanphoidetail', ['id' => 1]) }}"> TIẾP THEO</a>
            </div>
        </div>
    </div>





@endsection

resources/views/tracks/track2/reviews/phanphoi/detail-1.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-so-luoc-chuoi-khoi.png') }}" alt="">
    </div>
    <div class="review-detail-content phanphoi-detail">
        <div class="review-flex-center">
            <div class="box-label">
             <p>  Để phân phối sản phẩm đến đa dạng khách hàng trên toàn quốc, sản phẩm sau khi sản xuất sẽ được lưu trữ tại Kho thành phẩm của nhà máy hoặc các <span>Trung tâm phân phối</span>. Từ đó, sau khi đơn đặt hàng được xác nhận, sản phẩm sẽ được <span>phân phối theo 1 trong 2 kênh (Trực tiếp, Gián tiếp)</span>, ứng với các <span>tệp khách hàng khác nhau</span> như sau:</p>
            </div>
     
        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track2.review.phanphoi') }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track2.review.phanphoidetail', ['id' => $nextId]) }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track2/reviews/phanphoi/detail-3.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-cac-yeu-to-thanh-cong.png') }}" alt="">
    </div>
    <div class="review-detail-content kehoach-detail detail-3 sanxuat-detail ">
    


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track2.review.phanphoidetail', ['id' => $backId]) }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track2.review.phattrienthitruong') }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track2/reviews/phattrienthitruong.blade.php
@extends('layouts/review')
@section('track_number', 'track-2')
@section('content')
    <div class="phanphoi-index">
        <div class="box-title">
            <p> Sau khâu Phân phối với những kênh phát triển, phương tiện, mạng lưới Logistics thật đa dạng, hãy cùng tìm hiểu thêm về một khâu cực kỳ quan trọng giúp cho Thị Trấn mang những sản phẩm của mình tới thị trường một cách tốt nhất – khâu Phát triển thị trường:
            </p>
        </div>
        <div class="box-label phanphoi-box-label">
            <p>Hoạt động Phát triển thị trường xoay quanh 2 nhóm vai trò chính là <span>Thương mại</span> (Commercial) và <span>Bán hàng</span>(Sales), để đảm bảo việc phối hợp xây dựng chiến lược thương mại và thực thi bán hàng ở thị trường được triển khai hiệu quả nhất.</p>
        </div>
        <div class="rows-3">
            <div class="row-item phanphoi-label-item">
                <a href="{{ route('tracks.track2.review.phattrienthitruongdetail', ['id' => 1]) }}"><img
                        src="{{ asset('img/phanphoi-1.png') }}" alt=""></a>
            </div>
            <div class="row-item phanphoi-label-item">
                <a href="{{ route('tracks.track2.review.phattrienthitruongdetail', ['id' => 2]) }}"><img
                        src="{{ asset('img/phanphoi-2.png') }}" alt=""></a>
            </div>
            <div class="row-item phanphoi-label-item">
                <a href="{{ route('tracks.track2.review.phattrienthitruongdetail', ['id' => 3]) }}"><img
                        src="{{ asset('img/phanphoi-3.png') }}" alt=""></a>
            </div>
        </div>
        <div class="review-buttons">
            <div class="btn-back">
                <a href="{{ route('tracks.track2.review.index') }}">TRỞ LẠI</a>
            </div>
            <div class="btn-next">
                <a href="{{ route('tracks.track2.review.phattrienthitruongdetail', ['id' => 1]) }}"> TIẾP THEO</a>
            </div>
        </div>
    </div>





@endsection

resources/views/tracks/track2/reviews/phattrienthitruong/detail-1.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-thuong-mai.png') }}" alt="">
    </div>
    <div class="review-detail-content">
        <div class="review-flex-center">
            <div class="box-label">
                <p>Hoạt động thương mại của chúng ta thống nhất và gắn chặt với định hướng của OU, người đóng vai trò xương sống trong việc: </p>
                   <p> •Phát triển Nhận diện thương hiệu</p>
                    <p>•Truyền thông và quảng bá nhãn hàng</p>
                   <p> •Chiến lược đổi mới/ phát triển nhóm sản phẩm</p>
            </div>
      
        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track2.review.phattrienthitruong') }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track2.review.phattrienthitruongdetail', ['id' => $nextId]) }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track2/reviews/phattrienthitruong/detail-3.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-cac-chi-so-thanh-cong.png') }}" alt="">
    </div>
    <div class="review-detail-content kehoach-detail detail-3 sanxuat-detail ">
        <div class="review-flex-center">
            <div class="rows-3">
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/fluent_autosum-16-filled.png') }}" alt="">
                    </div>
                    <p> Tổng năng suất chuỗi cung ứng</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/icon-park-outline_manual-gear.png') }}" alt="">
                    </div>
                    <p> Hiệu quả hoạt động dây chuyền</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/healthicons_chart-death-rate-increasing.png') }}" alt="">
                    </div>
                    <p> Tỉ lệ sử dụng nước & năng lượng</p>
                </div>
            </div>


        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track2.review.phattrienthitruongdetail', ['id' => $backId]) }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track3.review.index') }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track3/reviews/hotro/detail-1.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-bo-phan-tai-chinh.png') }}" alt="">
    </div>
    <div class="review-detail-content">
        <div class="review-flex-center">
            <div class="box-label">
                <p>Tại thành phố hạnh phúc, bộ phận Tài chính có vai trò quản lý nguồn vốn, cơ cấu vốn, kế toán, các quyết định đầu tư, và cung cấp thông tin tài chính hỗ trợ cho việc ra quyết định. Hãy nhấp vào để mở khóa thông tin mô tả của 6 chức năng sau đây cho bộ phận Tài chính nhé:</p>
            </div>
      
        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track3.review.index') }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track3.review.hotrodetail', ['id' => $nextId]) }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track3/reviews/hotro/detail-3.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-bo-phap-ly.png') }}" alt="">
    </div>
    <div class="review-detail-content kehoach-detail detail-3 sanxuat-detail ">
     


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track3.review.hotrodetail', ['id' => $backId]) }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track3.review.hotrodetail',['id' => $nextId]) }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection

resources/views/tracks/track3/reviews/hotro/detail-4.blade.php
@extends('layouts/review')
@section('content')
    <div class="review-tag-label">
        <img src="{{ asset('img/tab-label-bo-phap-ly-2.png') }}" alt="">
    </div>
    <div class="review-detail-content kehoach-detail detail-3 sanxuat-detail ">
        <div class="review-flex-center">
            <div class="rows-3">
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/fluent_autosum-16-filled.png') }}" alt="">
                    </div>
                    <p> Tổng năng suất chuỗi cung ứng</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/icon-park-outline_manual-gear.png') }}" alt="">
                    </div>
                    <p> Hiệu quả hoạt động dây chuyền</p>
                </div>
                <div class="box-label d-flex style-2">
                    <div class="box-label-icon">
                        <img src="{{ asset('img/healthicons_chart-death-rate-increasing.png') }}" alt="">
                    </div>
                    <p> Tỉ lệ sử dụng nước & năng lượng</p>
                </div>
            </div>


        </div>


    </div>
    <div class="review-buttons">
        <div class="btn-back">
            <a href="{{ route('tracks.track3.review.hotrodetail', ['id' => $backId]) }}">TRỞ LẠI</a>
        </div>
        <div class="btn-next">
            <a href="{{ route('tracks.track3.review.index') }}"> TIẾP THEO</a>
        </div>
    </div>
@endsection